# Generated by Django 5.1 on 2024-08-31 09:18

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Datum vytvoření')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Datum aktualizace')),
                ('name', models.CharField(max_length=254, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True, verbose_name='Phone number')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='Company')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Position')),
                ('hours_ordered', models.DecimalField(blank=True, decimal_places=1, help_text='Hours in 0.5 steps', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999.5)], verbose_name='Hours ordered')),
                ('hours_delivered', models.DecimalField(blank=True, decimal_places=1, help_text='Hours in 0.5 steps', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999.5)], verbose_name='Hours delivered')),
                ('coaching_goal', models.TextField(blank=True, help_text='Client goal as per ICF definition', verbose_name='Coaching goal')),
                ('next_session_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Next session date and time')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_coach', to=settings.AUTH_USER_MODEL, verbose_name='Coach')),
            ],
            options={
                'verbose_name_plural': 'clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CoachingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Datum vytvoření')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Datum aktualizace')),
                ('datetime', models.DateTimeField(verbose_name='Date and time')),
                ('duration', models.DecimalField(decimal_places=1, help_text='Duration in hours', max_digits=3, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(12)], verbose_name='Duration')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('homework', models.TextField(blank=True, verbose_name='Homework')),
                ('realized', models.BooleanField(default=False, verbose_name='Realized')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_client', to='coach.client', verbose_name='Client')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_coach', to=settings.AUTH_USER_MODEL, verbose_name='Coach')),
            ],
            options={
                'verbose_name_plural': 'coaching sessions',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Datum vytvoření')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Datum aktualizace')),
                ('is_coach', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'choaches',
            },
        ),
    ]
