# Generated by Django 5.1 on 2024-08-31 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='user',
        ),
    ]
