# Generated by Django 5.1 on 2024-08-31 08:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0002_remove_client_coach_remove_coach_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='coaching_goal',
            field=models.TextField(blank=True, help_text='Client goal as per ICF definition', verbose_name='Coaching goal'),
        ),
        migrations.AlterField(
            model_name='client',
            name='hours_delivered',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Hours in 0.5 steps', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999.5)], verbose_name='Hours delivered'),
        ),
        migrations.AlterField(
            model_name='client',
            name='hours_ordered',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Hours in 0.5 steps', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999.5)], verbose_name='Hours ordered'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=254, verbose_name='Full Name'),
        ),
    ]
