# Generated by Django 5.1 on 2024-09-04 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0007_alter_coachingsession_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='next_session_datetime',
        ),
    ]
