# Generated by Django 5.1 on 2024-09-04 15:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0008_remove_client_next_session_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachingsession',
            name='datetime',
        ),
        migrations.AddField(
            model_name='coachingsession',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='coachingsession',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Time'),
        ),
    ]
