# Generated by Django 5.1 on 2024-09-05 20:02

import django.utils.timezone
import findacoach.coach.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0009_remove_coachingsession_datetime_coachingsession_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coachingsession',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='coachingsession',
            name='time',
            field=models.TimeField(default=findacoach.coach.models.current_time, verbose_name='Time'),
        ),
    ]
